export const site = {
  name: "Radha Sarveshwar Heritage Centre",
  shortName: "RSHC",
  slogan: "The world is one family",
  hindiSlogan: "वसुधैव कुटुम्बकम्",
  tagline: "Hindu temple near Brampton & Halton Hills, Ontario",
  description:
    "Radha Sarveshwar Heritage Centre is a Hindu temple (mandir) in Norval, Halton Hills, minutes from Brampton and Georgetown, Ontario. Open daily 7 AM – 8 PM.",
  url: "https://www.radhasarveshwar.org",
  email: "radhasarveshwarheritage@outlook.com",
  hours: {
    label: "Open daily",
    time: "7:00 AM – 8:00 PM",
    schema: "Mo-Su 07:00-20:00",
    opens: "07:00",
    closes: "20:00",
  },
  address: {
    line1: "9386 Tenth Line North",
    line2: "Norval, ON L0P 1K0",
    city: "Norval",
    region: "Ontario",
    regionCode: "ON",
    postal: "L0P 1K0",
    country: "Canada",
    countryCode: "CA",
    /** Official Google listing shared by the centre */
    googleListingUrl: "https://share.google/N76Eq6bWxRppb4Gg2",
    googleKnowledgeGraphId: "/g/11zdskbnnb",
    mapsUrl: "https://share.google/N76Eq6bWxRppb4Gg2",
    directionsUrl:
      "https://www.google.com/maps/dir/?api=1&destination=9386+Tenth+Line+North,+Norval,+ON+L0P+1K0",
    embedUrl:
      "https://www.google.com/maps?q=9386+Tenth+Line+North,+Norval,+ON+L0P+1K0&output=embed",
  },
  geo: {
    latitude: 43.6467673,
    longitude: -79.858421,
  },
  phones: [
    {
      id: "main",
      display: "+1 647-448-4975",
      tel: "+16474484975",
      href: "tel:+16474484975",
    },
    {
      id: "temple",
      display: "+1 647-710-9584",
      tel: "+16477109584",
      href: "tel:+16477109584",
    },
  ],
  serviceArea: {
    cities: [
      "Norval",
      "Georgetown",
      "Halton Hills",
      "Brampton",
      "Mississauga",
      "Milton",
      "Caledon",
      "Acton",
    ],
    regions: [
      "Peel Region",
      "Halton Region",
      "Greater Toronto Area",
      "Southern Ontario",
    ],
  },
  pandit: {
    name: "Pandit Mahesh Kumar Acharya",
    jobTitle: "Resident Pandit",
    image: "/images/pandit-mahesh-kumar-acharya.jpg",
  },
  keywords: [
    "Radha Sarveshwar Heritage Centre",
    "Hindu temple Brampton",
    "Hindu temple near Brampton",
    "Hindu temple Halton Hills",
    "Hindu temple Georgetown",
    "Hindu temple Norval",
    "Hindu temple Mississauga",
    "Hindu temple Milton",
    "Hindu temple Caledon",
    "Hindu temple Southern Ontario",
    "Hindu temple GTA",
    "mandir Brampton",
    "mandir near me Ontario",
    "Radha Krishna temple Ontario",
    "puja booking Brampton",
    "pandit in Brampton",
    "Diwali Brampton temple",
    "Navratri Halton Hills",
    "Sanatan Dharma Ontario",
    "Hindu heritage centre Canada",
  ],
} as const;
